name: Release to Nuget

on:
  push:
    tags: 
      - '**'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    
    - name: Create NuGet Package
      run: dotnet pack -c Release 
              /p:Version=${{  github.ref_name }}
              /p:PackageReleaseNotes="See https://github.com/AboimPinto/MaterialDesign.Avalonia/releases/tag/${{  github.ref_name }}"

    - name: Archive NuGet Package
      uses: actions/upload-artifact@v3
      with:
        name: MaterialDesign.Avalonia.PackIcon
        path: /home/runner/work/MaterialDesign.Avalonia/MaterialDesign.Avalonia/source/MaterialDesign.Avalonia.PackIcon/bin/Release/MaterialDesign.Avalonia.PackIcon.${{  github.ref_name }}.0.nupkg

    - name: Publish Nuget Package
      run: dotnet nuget push /home/runner/work/MaterialDesign.Avalonia/MaterialDesign.Avalonia/source/MaterialDesign.Avalonia.PackIcon/bin/Release/MaterialDesign.Avalonia.PackIcon.${{  github.ref_name }}.0.nupkg
              --api-key ${{ secrets.MATERIALDESIGN_AVALONIA_PACKICON_KEY }} 
              --source https://api.nuget.org/v3/index.json 
              --no-symbols true
