name: Release to Nuget

on:
  push:
    branches: [ master ]
  # release:
  #   types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Create NuGet Package
      run: dotnet pack -c Release 
              /p:Version=1.25.0 
              /p:PackageReleaseNotes="See https://github.com/AboimPinto/MaterialDesign.Avalonia/releases/tag/1.25.0"
              # /p:PackageReleaseNotes="See https://github.com/AboimPinto/MaterialDesign.Avalonia/releases/tag/${{ github.event.release.tag_name }}"

    - name: Archive NuGet Package
      uses: actions/upload-artifact@v3
      with:
        name: MaterialDesign.Avalonia.PackIcon
        path: /home/runner/work/MaterialDesign.Avalonia/MaterialDesign.Avalonia/source/MaterialDesign.Avalonia.PackIcon/bin/Release/MaterialDesign.Avalonia.PackIcon.1.25.0.nupkg
        # path: ./source/MaterialDesign.Avalonia.PackIcon/bin/Release/MaterialDesign.Avalonia.PackIcon.${{ github.event.release.tag_name }}.0.nupkg

    - name: Publish Nuget Package
      run: dotnet nuget push /home/runner/work/MaterialDesign.Avalonia/MaterialDesign.Avalonia/source/MaterialDesign.Avalonia.PackIcon/bin/Release/MaterialDesign.Avalonia.PackIcon.1.25.0.nupkg
              --api-key ${{ secrets.MATERIALDESIGN_AVALONIA_PACKICON_KEY }} 
              --source https://api.nuget.org/v3/index.json --no-symbols true
